INSERT INTO BENEFICIO (NOME, DESCRICAO, VALOR, ATIVO) VALUES ('Beneficio A', 'Descrição A', 1000.00, TRUE);
INSERT INTO BENEFICIO (NOME, DESCRICAO, VALOR, ATIVO) VALUES ('Beneficio B', 'Descrição B', 500.00, TRUE);
INSERT INTO BENEFICIO (NOME, DESCRICAO, VALOR, ATIVO) VALUES ('Beneficio C', 'Descrição C', 777.00, TRUE);
INSERT INTO BENEFICIO (NOME, DESCRICAO, VALOR, ATIVO) VALUES ('Beneficio D', 'Descrição D', 666.00, TRUE);
INSERT INTO BENEFICIO (NOME, DESCRICAO, VALOR, ATIVO) VALUES ('Beneficio E', 'Descrição E', 555.00, TRUE);
INSERT INTO BENEFICIO (NOME, DESCRICAO, VALOR, ATIVO) VALUES ('Beneficio E', 'Descrição F', 444.00, TRUE);